config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins
    resources :subjects
    resources :questions
  end

  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    get 'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end

  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    get 'zip_code', to: 'zip_code#show'
  end

  devise_for :users
  devise_for :admins, skip: [:registrations]

  get 'inicio', to: 'site/welcome#index'
  get 'backoffice', to: 'admins_backoffice/welcome#index'

  root to: 'site/welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/site/answer_controller.rb
class Site::AnswerController < SiteController
  def question
    @redis_answer = Rails.cache.fetch(params[:answer_id])
    @redis_answer.present? ? set_redis_answer : set_database_answer

    UserStatistic.set_statistic(@answer_is_correct, current_user)
  end

  private
    def to_bool(string)
      ActiveModel::Type::Boolean.new.cast(string)
    end

    def set_redis_answer
      splited_redis_answer = @redis_answer.split("@@")

      @question_id = splited_redis_answer.first
      @answer_is_correct = to_bool(splited_redis_answer.last)
    end

    def set_database_answer
      answer = Answer.find(params[:answer_id])

      @question_id = answer.question_id
      @answer_is_correct = answer.correct
    end
end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
  def questions
    @questions = Question.search_by(params[:page], params[:term])
  end

  def subject
    @questions = Question.search_by_subject(params[:page], params[:subject_id])
  end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
    @questions = Question.last_questions(params[:page])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
  def msg_jumbotron
    case params[:action]
    when 'index'
      "Últimas perguntas cadastradas..."
    when 'questions'
      "Resultados para o termo \"#{params[:term]}\"..."
    when 'subject'
      "Mostrando questões para o assunto \"#{params[:subject]}\""
    end
  end
end

app/views/site/shared/_questions.html.erb
<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
  <h3><%= msg_jumbotron %></h3>
</div>

<% @questions.each do |question| %>
  <%= form_with url: site_answer_path do |form| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <span class="label label-info" style="margin-right: 10px">
            <%= link_to "#{question.subject.description} (#{question.subject.questions_count})", site_search_subject_path(question.subject_id, question.subject.description), style: "color: white" %>
          </span>
          <%= question.description %>
        </h3>
      </div>
      <div class="panel-body">
        <ul>
          <% question.answers.each do |answer| %>
            <li style="list-style: none">
              <div class="radio">
                <label>
                  <%= radio_button_tag 'answer_id', answer.id %>
                  <%= answer.description %>
                </label>
              </div>
            </li>
          <% end %>

          <li style="list-style: none">
            <%= form.submit "Responder", class: "btn btn-default", id: "submit_#{question.id}" %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <div class="text-center">
    <%= paginate @questions %>
  </div>
<% else %>
  <div class="alert alert-warning" role="alert">
    Efetue login para poder continuar respondendo as questões...
  </div>
<% end %>